### ISSUE TITLE
Move into core?

### ISSUE THREAD

**Issue by wmhilton** [stoplightio/types#2]
@marbemac creating all these new repos (graph, types) undermines the power of the core submodule. The way I see it, we should be moving towards fewer repos, not more.

(I say we should move graph into core as well, particularly if you're going to Copy & Paste parts of core into other modules as a stop-gap.)

**Comment by marbemac** [comment]
The tricky bit is we are open sourcing things that need to depend on stuff like types (spectral, prism, maybe graph).

In general, we need to spend a little time thinking about domain lines for all of our stuff.

We can't add the private core repo as a submodule to the public prism repo, etc.

As of right now, I've been putting shared private code in core, and creating new repos for discrete public things (prism, spectral, graph). Ultimately we might want a public monorepo (or separate public repos, whatever) for `@stoplight/types`, `@stoplight/webpack`, `@stoplight/graph`, and other really generic things that can be public and need to be published.

Wide open for discussion.

**Comment by wmhilton** [comment]
I like the idea of two `core` repos - a private one and a public one.

I still think it makes the most sense in terms of efficiency to use the core repos as pure TS source code submodules. But for the public one we might come up with a script to build and publish them as npm modules as well. (Preferably with less maintenance hassle than it was maintaining `core`.)

If we want to re-use the build system (webpack scripts) in core in a public repo... it probably really makes sense to have an OSS core repo.

**Comment by marbemac** [comment]
I agree, should probably just go lerna for the public one - just need to be more diligent about how we split things up. What we did originally with core+lerna was far too granular to manage with published packages. Public repo rules:

## xyz should go in public repo if

1) More than one other package depends on it.
2) Company in general is OK putting it out into the open (case by case). 

## guidelines for deciding if xyz should have its own package

1) Adding it to an existing package would affect the supported environments for that package. IE adding expressjs helpers to a ui package would mean that ui package now only supports node.
2) It represents a valuable end "product" with clearly defined boundaries. IE `@stoplight/resolver`.
3) It carries a large dependency (looking at you monaco!)

## Suggested Starting Packages

1) `@stoplight/types`: anything that is used by more than one repository should be in here
2) `@stoplight/webpack`: all our webpack helpers
3) `@stoplight/reporter`: we should just put together a standard reporter for use everywhere - can wrap existing library if there is a good one that supports node and browsers.
4) `@stoplight/resolver`
5) `@stoplight/ui`: the low level, themeable component library that nick and will are working on

## Questions

1) Should discrete packages that might attract their own community be in separate repos, or in this public stoplight monorepo? Thinking about `@stoplight/spectral` and `@stoplight/resolver` right now. cc @rossmcdonald 
2) Where to put all the smaller utilities (path, json, text, etc). It is super annoying to have them all in separate packages. Perhaps they represent a small amount of code with tiny or no dependencies we put them all in a `@stoplight/common` or `@stoplight/utils` type package?

**Comment by wmhilton** [comment]
This keeps being the #1 google result for "stoplight/core" so I'm closing it 'cause that drives me nuts.
